apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
  namespace: argocd-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
      - name: app
        image: deviliam/argocd-test:latest
        ports:
        - containerPort: 80
