apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
  namespace: argocd-test
spec:
  replicas: 4
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
      - name: app
<<<<<<< HEAD
        image: deviliam/argocd-test:INIT
        imagePullPolicy: IfNotPresent
=======
        image: deviliam/argocd-test:5c32012fcb8456f9a97ce7f12eec521e71f1377a
>>>>>>> 9ae83cfe35a554f0c98931c5682019733d1131d0
        ports:
        - containerPort: 80
