apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
  namespace: argocd-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
      - name: app
        image: deviliam/argocd-test:7245c2cc3627e135c3e59258845336ef806ee23a
        ports:
        - containerPort: 80
