apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-test
  namespace: argocd-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-test
  template:
    metadata:
      labels:
        app: argocd-test
    spec:
      containers:
      - name: app
        image: deviliam/argocd-test:ea1a3de625c5a2804351258abb896a604ae42098
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
