apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-test
  namespace: argocd-test
spec:
  ingressClassName: nginx
  rules:
  - host: argotest.devilhai.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-test
            port:
              number: 80
